import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Code To Image App</title>

        <meta
          name="description"
          content="Convierte tu código en imágenes de forma rápida y sencilla con Code To Image App. Ideal para compartir tus proyectos en redes sociales y presentaciones."
        />

        <meta
          name="keywords"
          content="code, código, image, imagen, conversor, converter, desarrollo, programación, compartir, redes sociales, presentaciones"
        />

        <meta property="og:site_name" content="Code To Image App" />
        <meta property="og:title" content="Code To Image App" />
        <meta
          property="og:description"
          content="Convierte tu código en imágenes de forma rápida y sencilla con Code To Image App. Ideal para compartir tus proyectos en redes sociales y presentaciones."
        />
        <meta property="og:image" content="/code-to-image-converter.png" />
        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://code-to-img-project.vercel.app/"
        />

        <meta name="twitter:title" content="Code to Image App" />
        <meta name="twitter:description" content="Generated by Julio Condor" />
        <meta name="twitter:image" content="/code-to-image-converter.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
