import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:title" content="Code to Image App" />
        <meta property="og:description" content="Generated by Julio Condor" />
        <meta property="og:image" content="/code-to-image-converter.png" />

        {/* Agrega las etiquetas meta de Twitter */}
        <meta name="twitter:title" content="Code to Image App" />
        <meta name="twitter:description" content="Generated by Julio Condor" />
        <meta name="twitter:image" content="/code-to-image-converter.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
